flickr8k:
  dataset_class: StandardCaptionDataset
  captions_root: test_captions
  image_root: data
  excluded_files:
    - reference_captions.json

composite:
  dataset_class: StandardCaptionDataset
  captions_root: test_captions
  image_root: data
  excluded_files:
    - reference_captions.json

polaris:
  dataset_class: StandardCaptionDataset
  captions_root: test_captions
  image_root: data
  excluded_files:
    - reference_captions.json

noref_dataset: # dummy example, this is an example of how to config a reference free dataset
  dataset_class: ReferenceFreeDataset
  captions_root: test_captions
  image_root: data
  excluded_files:
    - reference_captions.json
